In [8]:

from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from time import sleep
import pandas as pd


#vdisplay = Xvfb()

#vdisplay.start()

url = 'https://www.rpachallenge.com/'
options = webdriver.ChromeOptions()

df = pd.read_excel('D:/Documentos/Dad√°/challenge.xlsx')

df

,First Name,Last Name,Company Name,Role in Company,Address,Email,Phone Number
0,John,Smith,IT Solutions,Analyst,98 North Road,jsmith@itsolutions.co.uk,40716543298
1,Jane,Dorsey,MediCare,Medical Engineer,11 Crown Street,jdorsey@mc.com,40791345621
2,Albert,Kipling,Waterfront,Accountant,22 Guild Street,kipling@waterfront.com,40735416854
3,Michael,Robertson,MediCare,IT Specialist,17 Farburn Terrace,mrobertson@mc.com,40733652145
4,Doug,Derrick,Timepath Inc.,Analyst,99 Shire Oak Road,dderrick@timepath.co.uk,40799885412
5,Jessie,Marlowe,Aperture Inc.,Scientist,27 Cheshire Street,jmarlowe@aperture.us,40733154268
6,Stan,Hamm,Sugarwell,Advisor,10 Dam Road,shamm@sugarwell.org,40712462257
7,Michelle,Norton,Aperture Inc.,Scientist,13 White Rabbit Street,mnorton@aperture.us,40731254562
8,Stacy,Shelby,TechDev,HR Manager,19 Pineapple Boulevard,sshelby@techdev.com,40741785214
9,Lara,Palmer,Timepath Inc.,Programmer,87 Orange Street,lpalmer@timepath.co.uk,40731653845

In [14]:
# inicia Chrome 



driver = webdriver.Chrome(executable_path='D:/Documentos/chromedriver/chromedriver.exe', options=options)




for index, row in df.iterrows():
    
    driver.get(url)
    first_name = driver.find_element_by_css_selector("input[ng-reflect-name='labelFirstName']")
    last_name = driver.find_element_by_css_selector("input[ng-reflect-name='labelLastName']")
    role = driver.find_element_by_css_selector("input[ng-reflect-name='labelRole']")
    company_name = driver.find_element_by_css_selector("input[ng-reflect-name='labelCompanyName']")
    phone = driver.find_element_by_css_selector("input[ng-reflect-name='labelPhone']")
    adress = driver.find_element_by_css_selector("input[ng-reflect-name='labelAddress']")
    email = driver.find_element_by_css_selector("input[ng-reflect-name='labelEmail']")

    first_name.send_keys(row["First Name"])
    last_name.send_keys(row["Last Name "])
    company_name.send_keys(row["Company Name"])
    role.send_keys(row["Role in Company"])
    adress.send_keys(row["Address"])
    email.send_keys(row["Email"])
    phone.send_keys(row["Phone Number"])



    driver.find_element_by_css_selector("input[type='submit']")

print ('Tchau ', (datetime.datetime.now()).strftime('%d/%m/%Y %H:%M:%S'))

sleep(10)

Tchau  15/02/2023 11:04:42